// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://royeatrorlsarqazgstm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJveWVhdHJvcmxzYXJxYXpnc3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDM5NjEsImV4cCI6MjA2ODU3OTk2MX0.8DQfE-WwkJYazrknRfb3Aol2B3QxHzY4GktHRQpdLMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});